# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - codecov/upload:
          token: CODECOV_TOKEN=34bab12a-47a2-4563-adc8-868d3aa6a495

workflows:
  example-workflow:
    jobs:
      - example-job
